__asm__(
".text \n"
".global " START " \n"
".type " START ",%function \n"
START ": \n"
"	movs a3, #0 \n"
"	mov fp, a3 \n"
"	mov lr, a3 \n"
"	ldr a2, 1f \n"
"	add a2, pc, a2 \n"
"	mov a1, sp \n"
"2:	subs a3, #16 \n"
"	ands a1, a3 \n"
"	mov sp, a1 \n"
"	bl " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
".align 2 \n"
"1:	.word _DYNAMIC-2b \n"
);
